# Generated by Django 5.0.6 on 2026-06-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_conversacion_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionwhatsapp',
            name='evolution_api_key',
        ),
        migrations.RemoveField(
            model_name='configuracionwhatsapp',
            name='evolution_api_url',
        ),
        migrations.RemoveField(
            model_name='configuracionwhatsapp',
            name='evolution_instance_name',
        ),
        migrations.RemoveField(
            model_name='configuracionwhatsapp',
            name='webhook_token',
        ),
        migrations.AddField(
            model_name='configuracionwhatsapp',
            name='meta_access_token',
            field=models.CharField(blank=True, help_text='Token de acceso permanente (System User) de Meta.', max_length=600),
        ),
        migrations.AddField(
            model_name='configuracionwhatsapp',
            name='meta_api_version',
            field=models.CharField(default='v21.0', max_length=20),
        ),
        migrations.AddField(
            model_name='configuracionwhatsapp',
            name='meta_app_secret',
            field=models.CharField(blank=True, help_text='App Secret de la app de Meta, para verificar la firma del webhook.', max_length=200),
        ),
        migrations.AddField(
            model_name='configuracionwhatsapp',
            name='meta_phone_number_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='configuracionwhatsapp',
            name='meta_verify_token',
            field=models.CharField(blank=True, help_text='Token que se configura en Meta al suscribir el webhook.', max_length=200),
        ),
        migrations.AddField(
            model_name='configuracionwhatsapp',
            name='meta_waba_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='WhatsApp Business Account ID'),
        ),
        migrations.AddField(
            model_name='plantillahsm',
            name='meta_categoria',
            field=models.CharField(choices=[('UTILITY', 'Utility'), ('MARKETING', 'Marketing'), ('AUTHENTICATION', 'Authentication')], default='UTILITY', max_length=20),
        ),
        migrations.AddField(
            model_name='plantillahsm',
            name='meta_estado',
            field=models.CharField(choices=[('local', 'No enviada a Meta'), ('PENDING', 'En revisión'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='plantillahsm',
            name='meta_idioma',
            field=models.CharField(default='es_AR', max_length=10),
        ),
        migrations.AddField(
            model_name='plantillahsm',
            name='meta_nombre',
            field=models.CharField(blank=True, help_text='Nombre técnico registrado en Meta (snake_case). Si está vacío, se genera del nombre.', max_length=512),
        ),
        migrations.AddField(
            model_name='plantillahsm',
            name='meta_rejected_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plantillahsm',
            name='meta_template_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
