# Generated by Django 5.0.6 on 2026-06-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0005_remove_configuracionwhatsapp_evolution_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionwhatsapp',
            name='proveedor',
            field=models.CharField(choices=[('meta', 'Meta Cloud API (oficial)'), ('twilio', 'Twilio')], default='meta', help_text='Proveedor de WhatsApp activo. Meta es más barato; Twilio es un intermediario (BSP).', max_length=20),
        ),
        migrations.AddField(
            model_name='configuracionwhatsapp',
            name='twilio_account_sid',
            field=models.CharField(blank=True, max_length=100, verbose_name='Twilio Account SID'),
        ),
        migrations.AddField(
            model_name='configuracionwhatsapp',
            name='twilio_auth_token',
            field=models.CharField(blank=True, help_text='Auth Token de Twilio, también valida la firma del webhook.', max_length=100),
        ),
        migrations.AddField(
            model_name='configuracionwhatsapp',
            name='twilio_whatsapp_from',
            field=models.CharField(blank=True, help_text='Número de WhatsApp habilitado en Twilio (ej. +14155238886).', max_length=40),
        ),
        migrations.AddField(
            model_name='plantillahsm',
            name='twilio_content_sid',
            field=models.CharField(blank=True, help_text='ContentSid de la plantilla creada en la consola de Twilio (empieza con HX).', max_length=64, verbose_name='Twilio ContentSid'),
        ),
    ]
